# Generated by Django 3.1.4 on 2021-01-05 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('task_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DummyTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.task')),
            ],
            bases=('core.task',),
        ),
        migrations.CreateModel(
            name='S3ToGoogleCloudStorageTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.task')),
                ('bucket', models.CharField(max_length=255)),
                ('prefix', models.TextField(max_length=255)),
                ('delimiter', models.TextField(max_length=255)),
                ('dest_gcs_conn_id', models.CharField(max_length=255)),
                ('dest_gcs', models.TextField(max_length=255)),
                ('replace', models.BooleanField(default=True, max_length=255)),
            ],
            bases=('core.task',),
        ),
        migrations.CreateModel(
            name='DagFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(default='No Description', max_length=255)),
                ('schedule_interval', models.CharField(default='', max_length=255)),
                ('start_date', models.CharField(default='', max_length=255)),
                ('owner', models.CharField(default='airflow', max_length=255)),
                ('depend_on_past', models.BooleanField(default=True)),
                ('email_on_failure', models.BooleanField(default=False)),
                ('retries', models.SmallIntegerField(default=0)),
                ('retry_delay', models.SmallIntegerField(default=5)),
                ('tasks', models.ManyToManyField(to='core.Task')),
            ],
        ),
    ]
