# Generated by Django 3.1.4 on 2021-01-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dagfile',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='core.Task'),
        ),
    ]
